### PR TITLE
Update AboutPage.qml

### PR DESCRIPTION
**Pull request by ghost**
some fix

### CODE REVIEW

**Comment by wdehoog** [comment]
Thanks

**Comment by ghost** [comment]
Hello sailor
I am waiting translation refresh, to translate the fix in AboutPages Ln:73 I need done that. Please. My main laptop the charger is broke I can not use the SF SDK ATM to send a PR with updates.

**Comment by wdehoog** [comment]
As you wish. Out of curiousity what can you do with the ts files without the SDK?

**Comment by ghost** [comment]
It is just to refresh *.ts file with lupdate. everything is good now.

**Pull request merged**
