### PR TITLE
Small fix -  donnie-nl.ts

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by wdehoog** [comment]
The thing is I do want the new-line to be in the string so there will be two lines in the dialog. Then there is a difference between what went wrong en what is the consequence.

**Comment by ghost** [comment]
You say you did it to have 2 lines in dialog box? You did  do it because the string of words is too big? or  why?

**Comment by ghost** [comment]
I think there are no consequences to doing it like you did it alone that does not look good doing that way, I can reverse all the changes on these word strings

**Edit:**  Killing PR.

**Comment by Caballlero** [comment]
- Or you can use
                horizontalAlignment: Text.AlignLeft
                truncationMode: TruncationMode.None
- on SectionHeader

**Comment by ghost** [comment]
@wdehoog  I think that could be fixed like adding: **Text Alignment on SectionHeader**

**Comment by wdehoog** [comment]
Well I meant I want something like:

[Notify terrible thing happened]
[Notify planned action will not be done]

So maybe I should have created two translatable messages.

**Comment by ghost** [comment]
ok you can leave it as it did and see if it works.
@wdehoog  how do you compile donnie? sailfish sdk?  because I see donnie in openrepos together with dependencies, so my question is why donnie dont compile with all built-in dependencies, and so only one packages. like donnie.rpm on openrepos.net without dependencies. I'm trying to compile it but at the end when I install it on my cell donnie does not boot.

**Comment by wdehoog** [comment]
I build donnie on the Sailfish IDE. 

The libraries it needs for building have to be installed on the build VM (Build Engine the call it). And not in on the VM but in the target on the VM. So for example adding the OBS repo:

sb2 -t SailfishOS-armv7hl -m sdk-install -R ssu ar wdehoog http://repo.merproject.org/obs/home:/wdehoog:/donnie/sailfishos_2.1.1.24/

The libraries it needs is libupnpp which needs libupnp6 and libupnp-devel.

The  libraries for running need to be installed on your phone (the SDK does not do this).
If you have installed donnie from openrepos on your phone all required libraries should be there.

All rpm's I have put on openrepos are build on OBS.

**Comment by ghost** [comment]
aah! as far as I know the sdk sailfish  it installs the built-in dependencies in the package for phone. I'll investigate that. I did  installed the donnie dependencies manually to build engine. then the sdk build donnie success but when i install in the phone the app not boot. I always used sdk to build sailfish package i never used  Sailfish IDE to build. Can you give some example to build donnie with  Sailfish IDE? I will thank you.

**Comment by wdehoog** [comment]
So the binaries and all the libraries are included in the same rpm? 

In theory you start the IDE , Open Project, choose donnie.pro and thats it. This Sailfish SDK is that also using a Virtual Machine?
(I work on Windows 10. I guess it is the same under Linux but I never tried.)

**Comment by ghost** [comment]
Yes, in the same binary.rpm;  on my test is 1.3MB
Yes you need virtual machine, jolla did it doing that way for compatibility with all platforms
**Well I use virtual machine to start build engine then i use the terminal to compile**

**Comment by ghost** [comment]
I can not build donnie with sailfish IDE :  ( can you send me your build at: carlosgonz@protonmail.com

**Pull request closed without merging**
