### PR TITLE
updating MultiItemPicker, AboutPage

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by wdehoog** [comment]
It looks like there is still a problem at [AboutPage.qml#L112](https://github.com/carlosgonzz/donnie/blob/0faa90734846c5dff434324e7d2fd87f8bd0abb9/qml/pages/AboutPage.qml#L112)

**Comment by wdehoog** [comment]
Hi,

I don't think this will work either. As far as I know strings cannot contain unescaped quotes. Do you mean something like:
```
"carlosgonz: " + qsTr("testing and UI rigor") + "\n"
"J.F.Dockes: upplay & libupnpp...
```

**Comment by ghost** [comment]
I am not sure If I fixed with the last commit, if not, feel free to close this PR, then add this to me and refresh *ts files, I will give many thanks,

**Comment by wdehoog** [comment]
Sorry for not giving time to your PR. I am over my head with a new project (hutspot). 
What do you mean with 'then add this to me'?

**Comment by ghost** [comment]
I say, If I can not fix, you fix it. I will give you thanks.
Yes I am tracking hutspot,nice app. You always create amazing app. As example; donnie is the best  upnp & cover action funtion with 3 buttons.

**Comment by ghost** [comment]
what about  patunnel-app? pulseaudio 11.1 is already in SF2.2

**Comment by wdehoog** [comment]
I tried to implement what you asked for. If not create an Issue and we can discuss there what you want.

**Comment by wdehoog** [comment]
There already is a patunnel app: https://github.com/vmatare/patunnel

**Comment by ghost** [comment]
I said if you have plan to launch ur patunel-fork, in openrepos it does not exist any patunel right now.

**Pull request closed without merging**
